In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
import pandas as pd

In [3]:
from pyace import *

# Using ACE potential as ASE calculator

## Copper

In [4]:
from ase.build import bulk

In [5]:
calc = PyACECalculator("Cu-III.yaml")

In [6]:
atoms = bulk("Cu","fcc", cubic=True)

In [7]:
# number of atoms
len(atoms)

4

In [8]:
atoms.set_calculator(calc)

In [9]:
atoms.get_potential_energy()

/home/users/lysogy36/miniconda3/envs/ace/lib/python3.8/site-packages/ase-3.21.1-py3.8.egg/ase/utils/__init__.py:41: FutureWarning: Please use atoms.cell.rank instead
  warnings.warn(warning)


-14.787742217244805

In [10]:
atoms.get_forces()

array([[ 4.13324973e-16, -6.37781928e-17, -5.19603891e-17],
       [ 3.22333306e-16, -6.49979202e-17,  1.74580944e-15],
       [-2.33201045e-15, -2.19008839e-17, -1.81910151e-15],
       [ 1.47676467e-15,  2.16298333e-17,  8.00412254e-17]])

Corresponding B-basis functions projections

In [11]:
projections = calc.projections

4 atoms by 62 functions

In [12]:
projections.shape

(4, 62)

In [13]:
projections

array([[ 2.28777629e+01,  1.66327213e+00,  5.88630544e+00,
         1.07790158e+01,  1.43294134e+01,  1.54380074e+01,
         1.44144919e+01,  1.26754667e+01,  1.18362896e+01,
         1.27302911e+01,  1.49215335e+01,  1.69861447e+01,
         1.73903665e+01,  1.54477790e+01,  1.17920480e+01,
         1.49217184e+02, -1.19520244e-33,  2.91864775e-31,
         1.81594541e+01,  4.63250635e-33, -1.10243341e-31,
         1.29443159e+02,  1.32784616e-32,  6.60313653e-31,
         2.20997183e+00, -7.09690547e-32,  4.73954387e-32,
         1.57529920e+01, -6.36093729e-32, -2.60157634e-31,
         1.12289557e+02, -1.54052676e-31,  1.82912452e-30,
         1.82275484e+03, -1.45999339e-32,  3.56525916e-30,
        -6.94226361e-50,  1.01886539e-46,  2.21825878e+02,
         5.65881431e-32, -1.34667186e-30, -1.77678483e-33,
        -1.02584973e-50, -2.28061139e-48,  4.33885416e-31,
        -4.45660046e-47,  2.69957973e+01, -8.66918839e-31,
         5.78956544e-31,  6.88667189e-33,  1.19952415e-4

## Ethanol

In [14]:
from ase.build import molecule

In [15]:
ethanol_calc = PyACECalculator("ethanol.yaml")

In [16]:
ethanol = molecule("CH3CH2OH", vacuum=10)

In [17]:
len(ethanol)

9

In [18]:
ethanol.set_calculator(ethanol_calc)

In [19]:
ethanol.get_potential_energy()

-45.09983065239134

In [20]:
ethanol.get_forces()

array([[-2.06556624e-01,  4.04103468e-01,  0.00000000e+00],
       [-4.65231835e-01, -7.42101899e-01,  2.22044605e-16],
       [ 6.89686362e-02, -1.65402173e-02,  4.44089210e-16],
       [-7.58088135e-02,  7.27635635e-02,  0.00000000e+00],
       [ 8.01448936e-02,  3.93828436e-01,  4.56710881e-01],
       [ 8.01448936e-02,  3.93828436e-01, -4.56710881e-01],
       [ 4.86479439e-01,  1.98578709e-01,  0.00000000e+00],
       [ 1.59297048e-02, -3.52230248e-01,  4.36002816e-01],
       [ 1.59297048e-02, -3.52230248e-01, -4.36002816e-01]])

9 atoms by 377 B-basis projections

In [21]:
ethanol_calc.projections.shape

(9, 377)

In [22]:
ethanol_calc.projections

array([[ 6.87003287e-01,  9.13102857e-02,  3.16696582e-01, ...,
         3.86724968e-02, -1.16955245e-03,  3.53701741e-05],
       [ 6.87003287e-01,  9.13102857e-02,  3.16696582e-01, ...,
         3.72481241e+00,  1.80696811e+00,  8.76590114e-01],
       [ 1.07633240e+00,  1.21385754e-01,  4.19337031e-01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       ...,
       [ 1.26554789e+00,  2.17250258e-01,  6.82653951e-01, ...,
         2.70555675e-03,  5.91968028e-05,  1.29520900e-06],
       [ 1.26973009e+00,  2.18301117e-01,  6.85798499e-01, ...,
         7.34446828e-02,  9.69071426e-03,  1.27864863e-03],
       [ 1.26973009e+00,  2.18301117e-01,  6.85798499e-01, ...,
         7.34446828e-02,  9.69071426e-03,  1.27864863e-03]])

# Compute projection for list of structures

In [23]:
from pyace.activelearning import compute_B_projections

In [24]:
#Let us make a list of three ethanol molecules
ethanol1 = molecule("CH3CH2OH", vacuum=10)
ethanol2 = molecule("CH3CH2OH", vacuum=5)
ethanol3 = molecule("CH3CH2OH", vacuum=2)

structures_list=[ethanol1, ethanol2, ethanol3]

In [25]:
ethanol_bconf=BBasisConfiguration("ethanol.yaml")

In [26]:
ethanol_projections=compute_B_projections(ethanol_bconf,
                                          atomic_env_list=structures_list)

100%|██████████| 3/3 [00:00<00:00, 1187.40it/s]


Finally, list of projections are grouped by different atom types (0,1,2 are corresponding to lexicographically sorted "C","H","O")

In [27]:
ethanol_projections

{0: array([[ 6.87003287e-01,  9.13102857e-02,  3.16696582e-01, ...,
          3.86724968e-02, -1.16955245e-03,  3.53701741e-05],
        [ 6.87003287e-01,  9.13102857e-02,  3.16696582e-01, ...,
          3.72481241e+00,  1.80696811e+00,  8.76590114e-01],
        [ 6.87003287e-01,  9.13102857e-02,  3.16696582e-01, ...,
          3.86724968e-02, -1.16955245e-03,  3.53701741e-05],
        [ 6.87003287e-01,  9.13102857e-02,  3.16696582e-01, ...,
          3.72481241e+00,  1.80696811e+00,  8.76590114e-01],
        [ 6.87003287e-01,  9.13102857e-02,  3.16696582e-01, ...,
          3.86724968e-02, -1.16955245e-03,  3.53701741e-05],
        [ 6.87003287e-01,  9.13102857e-02,  3.16696582e-01, ...,
          3.72481241e+00,  1.80696811e+00,  8.76590114e-01]]),
 1: array([[6.10636388e-01, 3.81706041e-02, 1.41910741e-01, ...,
         1.53741983e+00, 4.99668870e+00, 1.62394797e+01],
        [1.26467524e+00, 2.15426914e-01, 6.78569843e-01, ...,
         5.72478751e-01, 2.36621175e-01, 9.78020238e-0

In [28]:
# for 0: C (carbon) - 6 atoms in total in structures_list
ethanol_projections[0].shape

(6, 377)

In [29]:
# for 1: H (hydrogen) - 18 atoms in total
ethanol_projections[1].shape

(18, 377)

In [30]:
# for 2: O (oxygen) - 3 atoms in total
ethanol_projections[2].shape

(3, 377)

If you want to know to which of three structures certain H-atom belongs to, then provide option

In [31]:
ethanol_projections, structure_indices=compute_B_projections(ethanol_bconf,
                                          atomic_env_list=structures_list,
                                          structure_ind_list=range(len(structures_list)) )

100%|██████████| 3/3 [00:00<00:00, 1196.55it/s]


`ethanol_projections`  would be the same. 

But now you also have a mapping from atoms to correspongind structures:

In [32]:
structure_indices

{0: array([0, 0, 1, 1, 2, 2]),
 1: array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]),
 2: array([0, 1, 2])}

# Constructing the initial  ACE potential from scratch

Potentials above were already fitted, i.e. both radial functions and coefficients were optimized.

But one could construct *initial* potential, with zero coefficients and non-optimized radial functions.
See [Phys. Rev. Materials 6, 013804 Efficient parametrization of the atomic cluster expansion](https://journals.aps.org/prmaterials/abstract/10.1103/PhysRevMaterials.6.013804),APPENDIX C: RADIAL AND CUTOFF FUNCTIONS for explanations of radial functions opimization

In [33]:
from pyace import create_multispecies_basis_config

In this particular example we construct potential with different number of functions for Al and H

see https://pacemaker.readthedocs.io/en/latest/pacemaker/inputfile/#basis_configuration for more details of B-Basis construction

In [34]:
AlH_bbasis_configuration = create_multispecies_basis_config(
    {
    'deltaSplineBins': 0.001,
    'elements': ['Al', 'H'],

    'embeddings': {'ALL': {'drho_core_cut': 250,
                           'fs_parameters': [1, 1],
                           'ndensity': 1,
                           'npot': 'FinnisSinclair',
                           'rho_core_cut': 200000},
                   'Al': {'drho_core_cut': 250,
                          'fs_parameters': [1, 1, 1, 0.5],
                          'ndensity': 2,
                          'npot': 'FinnisSinclairShiftedScaled',
                          'rho_core_cut': 200000}

                   },

    'bonds': {'ALL': {'NameOfCutoffFunction': 'cos',
                      'core-repulsion': [10000.0, 5.0],
                      'dcut': 0.01,
                      'radbase': 'ChebPow',
                      'radparameters': [2.0],
                      'rcut': 3.9},

              ('Al', 'H'): {'NameOfCutoffFunction': 'cos',
                            'core-repulsion': [10000.0, 5.0],
                            'dcut': 0.01,
                            'radbase': 'ChebExpCos',
                            'radparameters': [2.0],
                            'rcut': 3.5},
              },

    'functions': {        
        # different number of unary functions for Al and H
        'Al': {
            'nradmax_by_orders': [10, 2, 2, 1],
            'lmax_by_orders':    [0,  1, 1, 1]
        },
        
        'H': {
            'nradmax_by_orders': [5, 2, 2],
            'lmax_by_orders':    [0,  1, 1]
        },
        
        # same number of binary functions

        'BINARY': {
            'nradmax_by_orders': [5, 1, 1],
            'lmax_by_orders': [0, 1, 1],
        },
    }
})

In [35]:
AlH_bbasis_configuration

BBasisConfiguration(deltaSplineBins=0.001, funcspecs_blocks=['Al H', 'H Al', 'Al', 'H', ])

In [36]:
AlH_bbasis_configuration.total_number_of_functions

84

## Option 1. Compute projections using PyACECalculator

One could construct PyACECalculator from B-basis configuration

In [37]:
AlH_calc = PyACECalculator(AlH_bbasis_configuration)

In [38]:
AlH_structure = bulk("Al",cubic=True)

In [39]:
AlH_structure*=(2,2,2) # create 2x2x2 supercell and replace first atom with H

AlH_structure[0].symbol='H'

There are 32 atoms, and first atom (index 0) is H

In [40]:
AlH_structure

Atoms(symbols='HAl31', pbc=True, cell=[8.1, 8.1, 8.1])

In [41]:
len(AlH_structure)

32

In [42]:
AlH_structure.set_calculator(AlH_calc)

Energy and forces are zero, because potential was initialized with zero coefficients

In [43]:
AlH_structure.get_potential_energy()

/home/users/lysogy36/miniconda3/envs/ace/lib/python3.8/site-packages/numpy/core/fromnumeric.py:43: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  result = getattr(asarray(obj), method)(*args, **kwds)


0.0

In [44]:
AlH_structure.get_forces()

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

nested list of B-babsis functions (not projections yet!)

In [45]:
b_basis_functions=AlH_calc.basis

There are two species types: Al - atom type 0, H - atom type 1

In [46]:
b_basis_functions.elements_to_index_map

{'Al': 0, 'H': 1}

First order B-functions (2-body): for first and second atoms types correspondingly

In [47]:
len(b_basis_functions.basis_rank1)

2

In [48]:
# 15 Al-centered (species type 0) pair functions:  10 Al-Al + 5 Al-H
species_type=0
b_basis_functions.basis_rank1[species_type]

[ACEBBasisFunction(0|mus=(0,), ns=(1,), ls=(0,), 1 ms_combs, ndens=2),
 ACEBBasisFunction(0|mus=(0,), ns=(2,), ls=(0,), 1 ms_combs, ndens=2),
 ACEBBasisFunction(0|mus=(0,), ns=(3,), ls=(0,), 1 ms_combs, ndens=2),
 ACEBBasisFunction(0|mus=(0,), ns=(4,), ls=(0,), 1 ms_combs, ndens=2),
 ACEBBasisFunction(0|mus=(0,), ns=(5,), ls=(0,), 1 ms_combs, ndens=2),
 ACEBBasisFunction(0|mus=(0,), ns=(6,), ls=(0,), 1 ms_combs, ndens=2),
 ACEBBasisFunction(0|mus=(0,), ns=(7,), ls=(0,), 1 ms_combs, ndens=2),
 ACEBBasisFunction(0|mus=(0,), ns=(8,), ls=(0,), 1 ms_combs, ndens=2),
 ACEBBasisFunction(0|mus=(0,), ns=(9,), ls=(0,), 1 ms_combs, ndens=2),
 ACEBBasisFunction(0|mus=(0,), ns=(10,), ls=(0,), 1 ms_combs, ndens=2),
 ACEBBasisFunction(0|mus=(1,), ns=(1,), ls=(0,), 1 ms_combs, ndens=2),
 ACEBBasisFunction(0|mus=(1,), ns=(2,), ls=(0,), 1 ms_combs, ndens=2),
 ACEBBasisFunction(0|mus=(1,), ns=(3,), ls=(0,), 1 ms_combs, ndens=2),
 ACEBBasisFunction(0|mus=(1,), ns=(4,), ls=(0,), 1 ms_combs, ndens=2),
 ACEB

In [49]:
# 10 H-centered (species type 1) pair functions:  5 H-Al + 5 H-H
species_type=1
b_basis_functions.basis_rank1[species_type]

[ACEBBasisFunction(1|mus=(0,), ns=(1,), ls=(0,), 1 ms_combs, ndens=1),
 ACEBBasisFunction(1|mus=(0,), ns=(2,), ls=(0,), 1 ms_combs, ndens=1),
 ACEBBasisFunction(1|mus=(0,), ns=(3,), ls=(0,), 1 ms_combs, ndens=1),
 ACEBBasisFunction(1|mus=(0,), ns=(4,), ls=(0,), 1 ms_combs, ndens=1),
 ACEBBasisFunction(1|mus=(0,), ns=(5,), ls=(0,), 1 ms_combs, ndens=1),
 ACEBBasisFunction(1|mus=(1,), ns=(1,), ls=(0,), 1 ms_combs, ndens=1),
 ACEBBasisFunction(1|mus=(1,), ns=(2,), ls=(0,), 1 ms_combs, ndens=1),
 ACEBBasisFunction(1|mus=(1,), ns=(3,), ls=(0,), 1 ms_combs, ndens=1),
 ACEBBasisFunction(1|mus=(1,), ns=(4,), ls=(0,), 1 ms_combs, ndens=1),
 ACEBBasisFunction(1|mus=(1,), ns=(5,), ls=(0,), 1 ms_combs, ndens=1)]

Higher order B-functions (3-body and more): for first and second atoms types correspondingly

In [50]:
# 31 Al-centered  higher order functions
species_type=0 # Al
b_basis_functions.basis[species_type]

[ACEBBasisFunction(0|mus=(0,0,), ns=(1,1,), ls=(0,0,), 1 ms_combs, ndens=2),
 ACEBBasisFunction(0|mus=(0,0,), ns=(1,1,), ls=(1,1,), 2 ms_combs, ndens=2),
 ACEBBasisFunction(0|mus=(0,0,), ns=(1,2,), ls=(0,0,), 1 ms_combs, ndens=2),
 ACEBBasisFunction(0|mus=(0,0,), ns=(1,2,), ls=(1,1,), 2 ms_combs, ndens=2),
 ACEBBasisFunction(0|mus=(0,0,), ns=(2,2,), ls=(0,0,), 1 ms_combs, ndens=2),
 ACEBBasisFunction(0|mus=(0,0,), ns=(2,2,), ls=(1,1,), 2 ms_combs, ndens=2),
 ACEBBasisFunction(0|mus=(0,1,), ns=(1,1,), ls=(0,0,), 1 ms_combs, ndens=2),
 ACEBBasisFunction(0|mus=(0,1,), ns=(1,1,), ls=(1,1,), 2 ms_combs, ndens=2),
 ACEBBasisFunction(0|mus=(1,1,), ns=(1,1,), ls=(0,0,), 1 ms_combs, ndens=2),
 ACEBBasisFunction(0|mus=(1,1,), ns=(1,1,), ls=(1,1,), 2 ms_combs, ndens=2),
 ACEBBasisFunction(0|mus=(0,0,0,), ns=(1,1,1,), ls=(0,0,0,), 1 ms_combs, ndens=2),
 ACEBBasisFunction(0|mus=(0,0,0,), ns=(1,1,1,), ls=(0,1,1,), 2 ms_combs, ndens=2),
 ACEBBasisFunction(0|mus=(0,0,0,), ns=(1,1,2,), ls=(0,0,0,), 1 m

In [51]:
# 28 H-centered higher order functions
species_type = 1 # H
b_basis_functions.basis[species_type]

[ACEBBasisFunction(1|mus=(0,0,), ns=(1,1,), ls=(0,0,), 1 ms_combs, ndens=1),
 ACEBBasisFunction(1|mus=(0,0,), ns=(1,1,), ls=(1,1,), 2 ms_combs, ndens=1),
 ACEBBasisFunction(1|mus=(0,1,), ns=(1,1,), ls=(0,0,), 1 ms_combs, ndens=1),
 ACEBBasisFunction(1|mus=(0,1,), ns=(1,1,), ls=(1,1,), 2 ms_combs, ndens=1),
 ACEBBasisFunction(1|mus=(1,1,), ns=(1,1,), ls=(0,0,), 1 ms_combs, ndens=1),
 ACEBBasisFunction(1|mus=(1,1,), ns=(1,1,), ls=(1,1,), 2 ms_combs, ndens=1),
 ACEBBasisFunction(1|mus=(1,1,), ns=(1,2,), ls=(0,0,), 1 ms_combs, ndens=1),
 ACEBBasisFunction(1|mus=(1,1,), ns=(1,2,), ls=(1,1,), 2 ms_combs, ndens=1),
 ACEBBasisFunction(1|mus=(1,1,), ns=(2,2,), ls=(0,0,), 1 ms_combs, ndens=1),
 ACEBBasisFunction(1|mus=(1,1,), ns=(2,2,), ls=(1,1,), 2 ms_combs, ndens=1),
 ACEBBasisFunction(1|mus=(0,0,0,), ns=(1,1,1,), ls=(0,0,0,), 1 ms_combs, ndens=1),
 ACEBBasisFunction(1|mus=(0,0,0,), ns=(1,1,1,), ls=(0,1,1,), 2 ms_combs, ndens=1),
 ACEBBasisFunction(1|mus=(0,0,1,), ns=(1,1,1,), ls=(0,0,0,), 1 m

In [52]:
len(AlH_structure)

32

Computed projections in `AlH_calc.projections`

In [53]:
len(AlH_calc.projections)

32

## Option 2. Compute projections using compute_B_projections

In [54]:
from pyace.activelearning import compute_B_projections

In [55]:
AlH_projections=compute_B_projections(AlH_bbasis_configuration,
                                          atomic_env_list=[AlH_structure])

100%|██████████| 1/1 [00:00<00:00, 890.89it/s]


In [56]:
AlH_projections

{0: array([[ 7.76542709e-01,  2.88689135e+00,  5.73512744e+00, ...,
          3.63631407e-01, -5.20519067e-03,  7.45095431e-05],
        [ 7.76542709e-01,  2.88689135e+00,  5.73512744e+00, ...,
          3.63631407e-01, -5.20519067e-03,  7.45095431e-05],
        [ 7.76542709e-01,  2.88689135e+00,  5.73512744e+00, ...,
          3.63631407e-01, -5.20519067e-03,  7.45095431e-05],
        ...,
        [ 8.47137501e-01,  3.14933602e+00,  6.25650266e+00, ...,
          5.15009962e-01, -4.32859932e-31,  3.63813779e-61],
        [ 8.47137501e-01,  3.14933602e+00,  6.25650266e+00, ...,
          5.15009962e-01, -4.32859932e-31,  3.63813779e-61],
        [ 8.47137501e-01,  3.14933602e+00,  6.25650266e+00, ...,
          5.15009962e-01, -4.19773190e-31,  3.42147811e-61]]),
 1: array([[ 9.52053451e-01,  6.53319771e-02,  2.43395019e-01,
          4.85312835e-01,  7.24681718e-01,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  9.06405774e-01, 

for Al (31 atoms by 46 B-functions):

In [57]:
AlH_projections[0].shape

(31, 46)

Corresponding to all basis functions for specie 0

In [69]:
len(b_basis_functions.basis_rank1[0]) + len(b_basis_functions.basis[0])

46

for H (1 atom by 38 B-functions):

In [58]:
AlH_projections[1].shape

(1, 38)

Corresponding to all basis functions for specie 1

In [68]:
len(b_basis_functions.basis_rank1[1])+len(b_basis_functions.basis[1])

38